### ISSUE TITLE
Is there a way to use multiple regex for different file mask?

### ISSUE THREAD

**Issue by mamatom** [UserUnknownFactor/filetranslate#1]
like this:

→→a-*.json→regex a→→
→→b-*.json→regex b→→
→→*.xml→regex c→→

a-01.json <- regex a
b-01.json <- regex b
c-01.xml <- regex c

**Comment by UserUnknownFactor** [comment]
Yes, just create different game profiles for each file mask and run the tool with `-g profile_name` for each of them.
This would go best with game-specific `game_regexps.csv` placed in the same directory as the project.
Masks like `a-*.json` should help in this case.
